services:
  redis:
    image: redis:alpine

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: tdoc
      POSTGRES_PASSWORD: tdoc
      POSTGRES_USER: tdoc

  backend:
    build: backend
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://tdoc:tdoc@db/tdoc
    ports:
      - 9000:9000
    depends_on:
      - redis
      - db
