services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: votes
      POSTGRES_PASSWORD: votes
      POSTGRES_USER: votes
    ports:
      - 5432:5432

  backend:
    build: backend
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://votes:votes@db/votes
    ports:
      - 9000:9000
    depends_on:
      - redis
      - db
