services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: tdoc
      POSTGRES_PASSWORD: tdoc
      POSTGRES_USER: tdoc

  backend:
    build: backend
    environment:
      DATABASE_URL: postgres://tdoc:tdoc@db/tdoc
    ports:
      - 9000:9000
    depends_on:
      - db
