name: Build and Push Backend Container

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        service: [backend]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Tag Name
        id: version
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Build Docker Image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ steps.version.outputs.tag }} ./${{ matrix.service }}
          docker tag ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ steps.version.outputs.tag }} ghcr.io/${{ github.repository }}/${{ matrix.service }}:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ steps.version.outputs.tag }}
          docker push ghcr.io/${{ github.repository }}/${{ matrix.service }}:latest
