name: Continuous Integration

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4
    - run: docker-compose run backend npm run lint
    - run: docker-compose run backend npm db:migrate:reset
    - run: docker-compose run backend npm test
